ddelnano/terraform-provider-mikrotik

go.mod
go.sum

I recently updated my RouterOS to the newest version and then running `terraform plan` gave me the following error.
```
invalid username or password
```
I then noticed that the routeros library had a fix for [this](https://github.com/go-routeros/routeros/pull/4)
Running `terraform plan` works again now.

Update the routeros library to fix login issues for RouterOS 6.43+

---

mikrotik/resource_dns_record.go
mikrotik/resource_dns_record_test.go

I didn't realize that terraform provided an out of the box import implementation if your record only imports with it's ID/name. This uses that implementation and also adds a test for it.

Simplify the implementation of the mikrotik_dns_record import and add acc test

---

client/client.go
client/script.go
mikrotik/resource_dns_record.go

This uses the log package to log errors, info and debug information. Previously I was using the fmt package which isn't how you are supposed to "log" inside terraform providers. The tests below show my intended change is working.
```
2019/10/01 17:20:53 [ERROR] Failed to login to routerOS with error: from RouterOS device: invalid user name or password (6)
```

Fix terraform provider debug logs

---

client/dns.go
mikrotik/resource_dns_record.go

Refactor the DNS code to match the other client return types

---

client/dns.go
client/errors.go
client/lease.go
client/lease_test.go
client/scheduler.go
client/scheduler_test.go
client/script.go
client/script_test.go
mikrotik/dns_test.go
mikrotik/resource_dhcp_lease_test.go
mikrotik/resource_dns_record.go
mikrotik/resource_dns_record_test.go
mikrotik/resource_scheduler_test.go
mikrotik/resource_script.go
mikrotik/resource_script_test.go

This is to address #15. The error handling across many of the mikrotik api client was inconsistent so it was possible for a client function to return a nil struct which then causes the terraform code to panic. I was able to test that the current master branch works for creating and destroying dns records so I believe the root of the issue is that the provider code isn't bubbling up the problem before it crashes.

Unify the error handling for mikrotik client code

---

README.md
antora.yml
scripts/dist.sh

This PR does the following things:
1. Remove the ability for the README to become out of date with the current set of resources and data sources. Users should look at the provider documentation to see what is supported
2. Remove a script that was used to build release binaries prior to switching to goreleaser
3. Removed the `antora.yml` which was used before documentation was hosted on the terraform registry

Cleanup readme and remove unused scripts

---

client/bgp_instance.go
client/bgp_instance_test.go
client/client.go
client/client_test.go
client/script.go
docs/resources/bgp_instance.md
mikrotik/provider.go
mikrotik/resource_bgp_instance.go
mikrotik/resource_bgp_instance_test.go

- Add support for [BPG Instance](https://wiki.mikrotik.com/wiki/Manual:Routing/BGP#Instance) resource
- Add Marshall function to `client.go` to construct  Mikrotik requests
- Add logic to Unmarshal to return `int` fields from RouterOS responses
- Move boolToMikrotikBool function to `client.go`

Add Marshalling and BGP Instance resource support

---

Makefile
client/lease.go
mikrotik/resource_dhcp_lease_test.go

This fixes #28. There was a problem with how the provider was encoding the string slice. The `strings.Split` function was splitting the comment value into multiple elements which was improperly encoded.
This change fixes this command building problem and add tests for multi word comments and ensures that the provider can correctly update the comment attribute.
```
ddelnano@ddelnano-desktop:~/go/src/github.com/ddelnano/terraform-provider-mikrotik$ make testacc
TF_ACC=1  go test ./... -v -count 1 -timeout 40m
?       github.com/ddelnano/terraform-provider-mikrotik [no test files]
=== RUN   TestAddBgpInstanceAndDeleteBgpInstance
2021/02/20 22:14:34 [INFO] Running the mikrotik command: `[/routing/bgp/instance/add =name=test-bgp =as=65533 =client-to-client-reflection=yes =disabled=no …
```

Fix comment bug issue 28

---

client/scheduler.go
client/script.go

This PR adds additional error to aid in debugging #39.

Add more error handling to scheduler and script client

---

.github/workflows/continuous-integration.yml
client/bgp_instance.go
client/bgp_instance_test.go
client/bgp_peer.go
client/bgp_peer_test.go
client/helpers.go
docs/resources/bgp_instance.md
docs/resources/bgp_peer.md
mikrotik/resource_bgp_instance.go
mikrotik/resource_bgp_instance_test.go
mikrotik/resource_bgp_peer_test.go

RouterOS v7 will not support the commands used by `mikrotik_bgp_peer` and `mikrotik_bgp_instance`. Instead there are new commands that will need their own corresponding resources. Let's get the CI build passing by skipping those resources.

Get CI job passing on RouterOS v7 by skipping bgp related tests that will never pass

---

client/dns.go
docs/resources/dns_record.md
mikrotik/resource_dns_record.go
mikrotik/resource_dns_record_test.go

Add comment argument to the mikrotik_dns_record resource

---

client/bgp_instance.go
client/bgp_peer.go
client/client.go
mikrotik/resource_bgp_instance.go
mikrotik/resource_bgp_peer.go
mikrotik/resource_dhcp_lease.go
mikrotik/resource_dns_record.go
mikrotik/resource_pool.go
mikrotik/resource_scheduler.go
mikrotik/resource_script.go

fixes #63, fixes #65 
Now instead of panic the output will look like:
```sh
mikrotik_pool.pool: Refreshing state... [id=*1]
mikrotik_script.bar: Refreshing state... [id=my_script]
╷
│ Error: from RouterOS device: invalid user name or password (6)
│ 
│   with mikrotik_pool.pool,
│   on main.tf line 16, in resource "mikrotik_pool" "pool":
│   16: resource "mikrotik_pool" "pool" {
│ 
╵
╷
│ Error: from RouterOS device: invalid user name or password (6)
│ 
│   with mikrotik_script.bar,
│   on main.tf line 22, in resource "mikrotik_script" "bar":
│   22: resource "mikrotik_script" "bar" {
```

fix: improve error handling in mikrotik/resourceRead() functions

---

client/client.go
client/client_test.go

fixes #68
As a side effect, I handled also an empty reply from RouterOS and return empty slice instead of panicing

fix: handle empty and 1-element replies from RouterOS when unmarshalling single value

---

client/pool.go
docs/resources/pool.md
mikrotik/resource_pool.go
mikrotik/resource_pool_test.go

This PR adds support of `next-pool` field to the `pool` resource.
Closes #23

[resource] add 'next-pool' field support to Pool

---

client/client.go
client/client_test.go
client/go.mod
client/go.sum
client/internal/types/list.go

This PR adds support for custom types with their own marshal/unmarshal process when using RouterOS client.
It works pretty much the same way as standard [json Marshaler](https://pkg.go.dev/encoding/json#Marshaler) interface.
The interface is:
```go
type (
// Marshaler interface will be used to serialize struct to RouterOS sentence
Marshaler interface {
// MarshalMikrotik serializes Go type value as RouterOS field value
MarshalMikrotik() string
}
// Unmarshaler interface will be used to de-serialize reply from RouterOS into Go struct
Unmarshaler interface {
// UnmarshalMikrotik de-serializes RouterOS field into Go type value
UnmarshalMikrotik(string) error
}
)
```
It is now possible to define custom type, e.g. `MikrotikList` so it is seamlessly converted to comma-separated list when the …

[client] add support for custom marshaling/unmarshaling

---

README.md

This PR adds instructions about local building of the provider.
It could be useful for those who are not familiar with Go and want to test the latest features

add local build section to readme

---

client/client.go
client/client_test.go

This PR adjusts logic in `client.go` related to Marshaling data before making API calls to a RouterOS device. While pairing with @DawoudMahmud on adding client support for creating Interface Wireguard resources (https://github.com/ddelnano/terraform-provider-mikrotik/pull/140, which is still a WIP), we came across Mikrotik documentation that lists some Wireguard properties to be ["Read Only](https://help.mikrotik.com/docs/display/ROS/WireGuard#WireGuard-Read-onlyproperties)".
This led to a test failure (see build [here](https://github.com/ddelnano/terraform-provider-mikrotik/actions/runs/4570066208/jobs/8066990862)) since a read-only boolean property `running` was included in the interface wireguard `add` command:
```
=== RUN   TestAddFindDeleteInterfaceWireguard
2023/03/30 23:54:57 …
```

Add client logic to support read-only Mikrotik properties

---

.goreleaser.yml

Since release change logs are automatically generated (#151) and given our acceptance tests give us strong validation that our code is functional, let's have `goreleaser` automatically publish releases. This will automate the final piece of manual work to create a release.
- Merge this change, create a `v0.11.0` tag and verify that a GitHub release is published automatically with our new release notes.

Update goreleaser to publish GitHub releases

---

.github/workflows/continuous-integration.yml
.github/workflows/release.yml
.github/workflows/tfplugindocs.yml
mikrotik/resource_scheduler.go

This PR adds a github workflow to prevent missing `tfplugindocs` updates (follow up for https://github.com/ddelnano/terraform-provider-mikrotik/pull/154). In addition to adding this workflow it upgrades the github action versions of setup-go and checkout for the existing workflows.

Add github workflow for `tfplugindocs` linting and unify setup-go and checkout action versions

---

README.md
cmd/mikrotik-codegen/internal/codegen/README.md
cmd/mikrotik-codegen/internal/codegen/generator_mikrotik.go
cmd/mikrotik-codegen/internal/codegen/generator_terraform.go
cmd/mikrotik-codegen/internal/codegen/templates.go
cmd/mikrotik-codegen/internal/utils/utils.go
cmd/mikrotik-codegen/internal/utils/utils_test.go
cmd/mikrotik-codegen/main.go

This PRs updates `cmd/mikrotik-codegen` utility to support MikroTik client resource generation alongside Terraform resource generation.

Codegen mikrotik resource

---

client/client.go
client/client_crud.go
client/ip_addr.go

This PR contains improvements to `client_crud` operations: new `List()` operation to enumerate resources is available.
`List()` returns a `slice of pointers` to MikroTik resources.

add client.List() support, refactor client ip_addr

---

client/bridge_vlan_test.go
client/helpers.go
client/scheduler.go
client/scheduler_test.go
mikrotik/resource_scheduler.go

This PR shows how to use `Generic..Resource` functions for Terraform resources (introduced in #161).
I created this PR against `terraform-model-client-struct-marshalling` branch to show only resource changes.
As you can see, the amount of code significantly reduced, so code generation could be done with less effort from our side - no need to implement `modelToXXXX()` and `XXXXToModel()` anymore

Poc generic crud functions

---

.github/workflows/continuous-integration.yml
README.md
client/bgp_instance_test.go
client/bgp_peer_test.go
client/helpers.go
client/interface_wireguard_test.go
client/ipv6_addr_test.go
client/setup.go
client/setup_test.go
client/system_resources.go
client/system_resources_test.go
mikrotik/acc_setup_test.go
mikrotik/resource_bgp_instance_test.go
mikrotik/resource_bgp_peer_test.go
mikrotik/resource_interface_wireguard_test.go
mikrotik/resource_ipv6_address_test.go

Prior to this change, we were using "legacy bgp support" or "wireguard support" environment variables as a proxy for RouterOS version detection. This change adds the necessary client support to dynamically determine what RouterOS version is in use and rely on that exclusively for all of our feature opt out/in.
This removes the need for providing environment variables to enforce this intent and fits better with what we wanted to originally express (whether a feature was supported on a given version or not).

Add helper functions for RouterOS version detection and use for feature opt out

---

mikrotik/resource_bgp_peer.go
mikrotik/resource_dhcp_lease.go
mikrotik/resource_interface_wireguard.go
mikrotik/resource_ipv6_address.go
mikrotik/resource_ipv6_address_test.go
mikrotik/resource_vlan_interface.go
mikrotik/resource_vlan_interface_test.go

Mark optional field as computed to prevent error after apply

---

mikrotik/internal/types/defaultaware/bool.go
mikrotik/internal/types/defaultaware/bool_test.go
mikrotik/internal/types/defaultaware/int64.go
mikrotik/internal/types/defaultaware/int64_test.go
mikrotik/internal/types/defaultaware/string.go
mikrotik/internal/types/defaultaware/string_test.go

This PR introduces wrapper types to generate Terraform docs with default value.
It is a drop-in replacement implemented as function.
To enable this feature, just wrap attribute in schema with proper typed wrapper:
```go
"address_pool": defaultaware.StringAttribute(
schema.StringAttribute{
Optional:    true,
Computed:    true,
Default:     stringdefault.StaticString("static-only"),
Description: "IP pool, from which to take IP addresses for the clients. If set to static-only, then only the clients that have a static lease (added in lease submenu) will be allowed.",
},
),
```
and next run of `make generate` will generate documentation with `Default: ....` suffix.

add Terraform wrapper types to generate docs with default value

---

mikrotik/resource_firewall_filter.go
mikrotik/resource_interface_list_member.go
mikrotik/resource_ip_address.go
mikrotik/resource_pool.go

This PR allows `import id` for resource to be in lowercase.
Both commands will act in the same way:
```shell
$ terraform import mikrotik_ip_address.this '*3e'
```
and
```shell
$ terraform import mikrotik_ip_address.this '*3E'
```

support case-insensitive IPAddress ID while importing

---

mikrotik/internal/utils/struct_copy.go
mikrotik/internal/utils/struct_copy_test.go
mikrotik/resource_generic_crud_operations.go
mikrotik/resource_pool.go

make copyStruct() function case-insensitive while searching for fields in structs

---

client/client.go
client/interface_wireguard_peer_test.go
mikrotik/resource_interface_wireguard_peer_test.go

client: fix marshaling of int64 type

---

client/interface_wireguard_peer.go
mikrotik/resource_interface_wireguard_peer_test.go

Fixes #221 
In MikroTik documentation, the `persistent_keepalive` [is defined](https://help.mikrotik.com/docs/display/ROS/WireGuard#WireGuard-Peers) as `Integer: A seconds interval, between 1 and 65535 inclusive.`
In fact, after client sets it, in all subsequent reads this field becomes a duration:
| Set value | Read value |
|:---------:|:-----------:|
| 20 | 20s |
| 123 | 2m3s |
| 3602 | 1h2s |
This PR changes `PersistentKeepalive` field type to our internal Duration type that can handle such normalizations.

fix: use Duration type for PersistentKeepalive field in InterfaceWireguardPeer

---

.gitignore
client/script.go
client/script_test.go
docs/resources/script.md
mikrotik/resource_script.go
mikrotik/resource_script_test.go

The `owner` attribute is readonly in RouterOS.
See [documentation](https://help.mikrotik.com/docs/spaces/ROS/pages/47579229/Scripting#Scripting-Scriptrepository)

fix script.owner attribute

---

.github/workflows/continuous-integration.yml
Makefile
bin/wait-for-routeros.sh
docker/docker-compose.yml

Sometimes, the `routeros` container is slow to start and `testclient`, `testacc` targets run against semi-working container.
This PR adds waiting logic.

improve stability of testing setup
